Repository Gongkademy/Gongkademy_Service_Back, pull requests merged in 2024-06, with the labels that each got.

#3 2 feat 초기 필요한 설정 추가
  .github/PULL_REQUEST_TEMPLAGE.md
  .gitignore
  src/main/resources/application.properties
Labels: ✨Feat, ♻️Refactor

#6 4 feat aws s3 설정
  build.gradle
  src/main/java/com/gongkademy/infra/s3/S3TestController.java
  src/main/java/com/gongkademy/infra/s3/config/S3Config.java
  src/main/java/com/gongkademy/infra/s3/service/FileService.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
  src/main/resources/application.properties
Labels: ✨Feat

#14 [Fix] test 코드 실행안되는 버그 수정
  build.gradle
  src/main/java/com/gongkademy/Application.java
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/service/MailSendService.java
  src/main/java/com/gongkademy/global/config/EmailConfig.java
  src/test/java/com/gongkademy/ApplicationTests.java
  src/test/java/com/gongkademy/repository/MemberRepositoryTest.java
  src/test/java/com/gongkademy/service/MemberServiceTest.java
  src/test/resources/application.properties
Labels: 🐛Fix

#17 feat: 회원 관련 초기 설정
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/dto/EmailCheckDto.java
  src/main/java/com/gongkademy/domain/member/dto/EmailRequestDto.java
  src/main/java/com/gongkademy/domain/member/dto/MemberPasswordUpdateDTO.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
  src/main/java/com/gongkademy/global/security/handler/APILoginFailureHandler.java
  src/main/java/com/gongkademy/global/security/handler/APILoginSuccessHandler.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/gongkademy/global/security/util/PasswordUtil.java
  src/main/resources/application.properties
  src/test/java/com/gongkademy/service/MemberServiceTest.java
Labels: ✨Feat

#18 Feat: 커뮤니티 초기 설정
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/controller/CommentLikeController.java
  src/main/java/com/gongkademy/domain/community/controller/PickController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/dto/request/BoardRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/request/CommentLikeRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/request/CommentRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/request/PickRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/CommentLikeResponseDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/PickResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/entity/board/BoardType.java
  src/main/java/com/gongkademy/domain/community/entity/board/ImageBoard.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/entity/comment/Comment.java
  src/main/java/com/gongkademy/domain/community/entity/comment/CommentLike.java
  src/main/java/com/gongkademy/domain/community/entity/comment/CommentType.java
  src/main/java/com/gongkademy/domain/community/entity/pick/Pick.java
  src/main/java/com/gongkademy/domain/community/entity/pick/PickType.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/repository/CommentLikeRepository.java
  src/main/java/com/gongkademy/domain/community/repository/CommentRepository.java
  src/main/java/com/gongkademy/domain/community/repository/PickRepository.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/BoardService.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/CommentLikeService.java
  src/main/java/com/gongkademy/domain/community/service/CommentLikeServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/CommentService.java
  src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/PickService.java
  src/main/java/com/gongkademy/domain/community/service/PickServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java
Labels: ✨Feat, 🐛Fix

#28 Feat: QnaBoard CRUD 작업 진행
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/dto/request/ImageRequestDto.java
  src/main/java/com/gongkademy/domain/community/dto/request/QnaBoardRequestDto.java
  src/main/java/com/gongkademy/domain/community/dto/response/ImageResponseDto.java
  src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDto.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
  src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java
Labels: ✨Feat, 🧪Test

#33 Feat : 공지사항 최신순 TOP3 (#32)
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/dto/request/BoardRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/BoardService.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/test/java/com/gongkademy/domain/community/controller/BoardControllerTest.java
  src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
Labels: ✨Feat, 🧪Test

#35 34 feat 댓글 기능 설정 및 리팩토링
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/dto/request/CommentRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/entity/comment/Comment.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/repository/CommentRepository.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/CommentService.java
  src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
  src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
Labels: ✨Feat, ♻️Refactor

#45 Refactor : QnaBoardDto Builer 패턴 적용 및 Member 변경사항 반영
  src/main/java/com/gongkademy/domain/community/dto/response/ImageResponseDto.java
  src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDto.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: ♻️Refactor

#47 Feat: 조회수 및 Pagenation 구현
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/PickServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
  src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
  src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java
Labels: ✨Feat

#50 Test: 테스트 및 리팩토링 진행
  src/main/java/com/gongkademy/domain/community/entity/board/ImageBoard.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
  src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java
Labels: 🧪Test, ♻️Refactor

#57 Feat: JWT관련 Filter & Handler 구현
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: ✨Feat, ♻️Refactor

#69 Feat 강의 플레이어 관련 기능 추가
  src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
  src/main/java/com/gongkademy/domain/course/dto/request/PlayerRequestDTO.java
  src/main/java/com/gongkademy/domain/course/dto/response/PlayerResponseDTO.java
  src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
  src/main/java/com/gongkademy/domain/course/repository/RegistLectureRepository.java
  src/main/java/com/gongkademy/domain/course/service/PlayerService.java
  src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#78 Feat: 마이페이지 강좌 관련 기능 작업
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseResponseDTO.java
  src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: ✨Feat

#83 Test : 기능 Test 및 수정
  src/main/java/com/gongkademy/domain/community/controller/PickController.java
  src/main/java/com/gongkademy/domain/community/dto/request/PickRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/PickResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/service/PickService.java
  src/main/java/com/gongkademy/domain/community/service/PickServiceImpl.java
  src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
  src/test/java/com/gongkademy/domain/community/service/CommentServiceImplTest.java
Labels: 🧪Test, ♻️Refactor

#85 Refactor: Board Entity 수정
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/dto/request/ImageRequestDto.java
  src/main/java/com/gongkademy/domain/community/dto/request/QnaBoardRequestDto.java
  src/main/java/com/gongkademy/domain/community/dto/response/ImageResponseDto.java
  src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDto.java
  src/main/java/com/gongkademy/domain/community/entity/board/ImageBoard.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
Labels: ♻️Refactor

#89 Feat: 좋아요 및 스크랩 메서드 작성
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: ✨Feat

#91 Feat: Consulting 게시판 (Controller, Service, Repo) 코드 작성
  src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/dto/request/QnaBoardRequestDTO.java
  src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
  src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java
Labels: ✨Feat

#92 84 feat 유저별 기능
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
  src/main/java/com/gongkademy/domain/community/service/CommentService.java
  src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
  src/test/java/com/gongkademy/domain/community/service/CommentServiceImplTest.java
Labels: ✨Feat, ♻️Refactor

#95 Feat: 강의 플레이어 관련 기능 추가
  src/main/java/com/gongkademy/domain/course/dto/response/PlayerResponseDTO.java
  src/main/java/com/gongkademy/domain/course/entity/RegistCourse.java
  src/main/java/com/gongkademy/domain/course/entity/RegistLecture.java
  src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#98 Refactor: course 도메인 authentication 추가
  src/main/java/com/gongkademy/domain/course/controller/CourseCommentController.java
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/controller/CourseReviewController.java
  src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
  src/main/java/com/gongkademy/domain/course/entity/Scrap.java
  src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
  src/main/java/com/gongkademy/domain/course/repository/ScrapRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseCommentService.java
  src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseReviewService.java
  src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/PlayerService.java
  src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#102 Fix: CourseLikeRepo 메서드명 수정
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: 🐛Fix

#105 Refactor: 강의 도메인 엔티티 수정
  src/main/java/com/gongkademy/domain/course/dto/request/CourseCommentRequestDTO.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseCommentResponseDTO.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseReviewResponseDTO.java
  src/main/java/com/gongkademy/domain/course/entity/Course.java
  src/main/java/com/gongkademy/domain/course/entity/CourseComment.java
  src/main/java/com/gongkademy/domain/course/entity/CourseReview.java
  src/main/java/com/gongkademy/domain/course/entity/Lecture.java
  src/main/java/com/gongkademy/domain/course/entity/Notice.java
  src/main/java/com/gongkademy/domain/course/entity/RegistCourse.java
  src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
Labels: ♻️Refactor

#110 Refactor : 상세조회 시 댓글불러오기
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/CommentService.java
Labels: ♻️Refactor

#111 108 refactor 공지사항 기능 수정
  src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
Labels: ♻️Refactor

#115 Fix : Entity DTO 에러 수정
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
Labels: 🐛Fix

#116 Feat: 키워드 기반 검색 기능 추가
  src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#133 Refactor: member createdate 관련 수정
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
Labels: ♻️Refactor

#135 Fix: Proxy -> Object 형 변환 문제 해결
  src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: 🐛Fix

#138 Feat: 강의 도메인 접근 권한 설정
  src/main/java/com/gongkademy/domain/course/controller/CourseCommentController.java
  src/main/java/com/gongkademy/domain/course/controller/CourseReviewController.java
  src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
  src/main/java/com/gongkademy/domain/course/entity/Course.java
  src/main/java/com/gongkademy/domain/course/repository/CourseReviewRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseCommentService.java
  src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseReviewService.java
  src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/course/service/PlayerService.java
  src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#139 Feat AWS 관련 기존 강좌 조회 기능 수정 및 기능 추가
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseInfoResponseDTO.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseResponseDTO.java
  src/main/java/com/gongkademy/domain/course/entity/Course.java
  src/main/java/com/gongkademy/domain/course/entity/CourseFile.java
  src/main/java/com/gongkademy/domain/course/repository/CourseFileRepository.java
  src/main/java/com/gongkademy/domain/course/repository/PreCourseRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
  src/test/java/com/gongkademy/domain/course/service/CourseServiceTest.java
Labels: ✨Feat, ♻️Refactor

#142 Fix:선수과목 repo 오류 해결
  src/main/java/com/gongkademy/domain/course/repository/PreCourseRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: 🐛Fix

#145 126 feat 좋아요 스크랩여부 확인
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/service/BoardService.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/test/java/com/gongkademy/domain/community/controller/BoardControllerTest.java
Labels: ✨Feat
