Repository Gongkademy/Gongkademy_Service_Back, pull requests merged in 2024-07, with the labels that each got.

#150 Refactor: JWTUtil token expired 관련 수정
  src/main/java/com/gongkademy/global/security/util/JWTUtil.java
Labels: ♻️Refactor

#152 Feat: 151 commentcontroller 에 알림 전송 기능 구현
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
Labels: ✨Feat

#155 Refactor: #154 CommentController 코드 리팩토링
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
Labels: ♻️Refactor

#157 Fix: #156 comment의 parentid 관련 오류 수정
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/repository/CommentRepository.java
Labels: 🐛Fix, ♻️Refactor

#158 Fix: 강좌 자료 다운로드 기능 수정 및 테스트
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/entity/CourseFile.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/infra/s3/S3TestController.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
Labels: 🧪Test, 🐛Fix

#161 Feat : ClassDiagram작성
  ClassDiagram.puml
Labels: ✨Feat

#163 [Refactor] member 필드 수정 대학,전공,부전공 삭제 + 마케팅동의 추가
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/dto/MemberSignUpDTO.java
  src/main/java/com/gongkademy/domain/member/dto/MemberUpdateDTO.java
  src/main/java/com/gongkademy/domain/member/dto/PrincipalDetails.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
Labels: ♻️Refactor

#165 Refactor: accesstoken을 cookie에서 추출하도록 변경
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/gongkademy/global/security/util/JWTUtil.java
Labels: ♻️Refactor

#167 Feat: 알림 관련 api 추가 구현
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/dto/PrincipalDetails.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/main/java/com/gongkademy/domain/member/repository/MemberRepository.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
  src/main/java/com/gongkademy/domain/notification/controller/NotificationController.java
  src/main/java/com/gongkademy/domain/notification/dto/response/NotificationResponseDTO.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationService.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#169 Fix: MemberRepository findIsNotificationEnabledById 메서드 수정
  src/main/java/com/gongkademy/domain/member/repository/MemberRepository.java
Labels: 🐛Fix

#171 Refactor: SecurityConfig 활성화 관련 수정
  src/main/java/com/gongkademy/Application.java
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
Labels: ♻️Refactor

#174 Refactor: UserDetailsServiceImpl 삭제 및 관련 코드 삭제
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/member/service/UserDetailsServiceImpl.java
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
Labels: ♻️Refactor

#175 Test: member 관련 테스트 코드 작성
  src/test/java/com/gongkademy/domain/member/service/MemberServiceImplTest.java
  src/test/java/com/gongkademy/repository/MemberRepositoryTest.java
Labels: 🧪Test

#183 Feat: 탈퇴회원 관련 클래스 구현
  src/main/java/com/gongkademy/domain/member/entity/WithdrawMember.java
  src/main/java/com/gongkademy/domain/member/repository/WithdrawMemberRepository.java
Labels: ✨Feat

#187 Fix: patch 메소드 Corsorigin 버그 수정
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
Labels: 🐛Fix

#193 Fix : 게시물 조회 기능 수정
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
  src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
  src/test/java/com/gongkademy/domain/community/service/CommentServiceImplTest.java
Labels: 🧪Test, 🐛Fix, ♻️Refactor

#196 Fix: Fix to Get Consult Boards
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
Labels: 🐛Fix

#198 Refactor: SecurityConfig 접근 권한 관련 수정
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
Labels: ♻️Refactor

#200 Fix: Fix to get Qna Boards
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: 🐛Fix

#214 Refactor: CourseEntity 수정
  src/main/java/com/gongkademy/domain/course/entity/Course.java
  src/main/java/com/gongkademy/domain/course/entity/PreCourse.java
Labels: ♻️Refactor

#216 Refactor: Course, PreCourse 변경에 따른 반영
  src/main/java/com/gongkademy/domain/course/dto/response/CourseInfoResponseDTO.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseResponseDTO.java
  src/main/java/com/gongkademy/domain/course/repository/PreCourseRepository.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: ♻️Refactor

#220 Refactor: MemberInfoDTO 내 member_role 필드명 수정
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
Labels: ♻️Refactor

#225 Refactor: SecurityConfig 내 필요 URL 변경
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
Labels: ♻️Refactor

#227 [Refactor] 회원 관련 Exception 처리 변경
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
Labels: ♻️Refactor

#232 Refactor: 알림 관련 Exception 처리 변경
  src/main/java/com/gongkademy/domain/notification/controller/NotificationController.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationService.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
Labels: ✨Feat, ♻️Refactor

#234 Refactor: OAuth2LoginSuccessHandler MAIN_URL 변경
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: ♻️Refactor

#236 Refactor: access token 중복 발급 수정
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: ♻️Refactor

#238 Refactor: oauth2memberservice 코드 리팩토링
  src/main/java/com/gongkademy/domain/member/repository/MemberRepository.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
Labels: ♻️Refactor

#240 Refactor: MemberRepositoryTest 코드 리팩토링
  src/test/java/com/gongkademy/repository/MemberRepositoryTest.java
Labels: ♻️Refactor

#244 243 refactor 탈퇴회원조회 repository 메서드 수정
  src/main/java/com/gongkademy/domain/member/repository/MemberRepository.java
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
Labels: ♻️Refactor

#252 fix: type에 따른 board 조회
  src/main/java/com/gongkademy/domain/community/entity/board/Board.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
Labels: 🐛Fix

#254 Refactor: pagination 반환값 수정
  src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#259 Refactor: JWTCheckFilter 토큰 Exception 처리 수정
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
  src/main/java/com/gongkademy/global/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
Labels: ✨Feat, ♻️Refactor

#261 Refactor: oauth2memberservice exception 처리 수정
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginFailureHandler.java
Labels: ♻️Refactor

#264 Refactor: 회원정보 조회시 id도 반환하도록 변경
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
Labels: ♻️Refactor

#278 Feat: 전체 강좌 목록 조회(비로그인) 구현
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseGuestResponseDTO.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: ✨Feat

#279 Feat: 강좌 목차 조회(비로그인) 구현
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/dto/response/CourseContentsGuestResponseDTO.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: ✨Feat

#280 Feat: 강좌 상세 조회(비로그인) 구현
  src/main/java/com/gongkademy/domain/course/controller/CourseController.java
  src/main/java/com/gongkademy/domain/course/service/CourseService.java
  src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
Labels: ✨Feat

#281 [FEAT] jwt 체크필터 적용안하는 URL 설정
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
  src/main/java/com/gongkademy/global/security/util/JWTUtil.java
Labels: ✨Feat

#284 Refactor: 부가정보 입력 로직 삭제
  src/main/java/com/gongkademy/domain/member/service/OAuth2MemberService.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/gongkademy/global/security/util/JWTUtil.java
Labels: ♻️Refactor

#285 Fix: jwtfilter에서 filter제외 url methods를 못불러오는 버그
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
  src/main/java/com/gongkademy/global/security/util/JWTUtil.java
Labels: 🐛Fix

#287 Refactor: access token refresh token 둘 다 만료 시 로직 추가
  src/main/java/com/gongkademy/global/config/SecurityConfig.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
  src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
  src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: ✨Feat, ♻️Refactor

#288 275 feat commentcontroller 권한별 로직 분리
  src/main/java/com/gongkademy/domain/community/controller/CommentController.java
  src/main/java/com/gongkademy/domain/community/service/CommentService.java
  src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationService.java
  src/main/java/com/gongkademy/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
Labels: ✨Feat, ♻️Refactor

#290 Refactor: No Content 상태코드 추가
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
Labels: ♻️Refactor

#293 refactor: 권한별 로직 분리 및 기능 추가
  src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
  src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
  src/main/java/com/gongkademy/domain/community/dto/response/ConsultingBoardResponseDTO.java
  src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
  src/main/java/com/gongkademy/domain/community/repository/PickRepository.java
  src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
  src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
  src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#295 274 feat boardcontroller 권한별 로직 분리
  src/main/java/com/gongkademy/domain/community/controller/BoardController.java
  src/main/java/com/gongkademy/domain/community/service/BoardService.java
  src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
Labels: ✨Feat

#299 Feat: 프론트 protected router를 위한 권한 검증 api 구현
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
Labels: ✨Feat

#301 Feat: 유저 프로필 사진 기능 추가
  src/main/java/com/gongkademy/domain/member/controller/MemberController.java
  src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/gongkademy/domain/member/dto/MemberUpdateDTO.java
  src/main/java/com/gongkademy/domain/member/entity/Member.java
  src/main/java/com/gongkademy/domain/member/service/MemberService.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/gongkademy/infra/s3/service/FileService.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
  src/test/java/com/gongkademy/domain/member/service/MemberServiceImplTest.java
Labels: ✨Feat, ♻️Refactor

#306 Refactor: S3 업로드 메서드 통합 구현
  src/main/java/com/gongkademy/domain/course/admin/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/course/common/entity/Course.java
  src/main/java/com/gongkademy/domain/course/common/entity/CourseFile.java
  src/main/java/com/gongkademy/domain/course/common/entity/CourseFileCateg.java
  src/main/java/com/gongkademy/domain/course/common/repository/CourseFileRepository.java
  src/main/java/com/gongkademy/domain/course/service/service/CourseServiceImpl.java
  src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/gongkademy/infra/s3/S3TestController.java
  src/main/java/com/gongkademy/infra/s3/service/FileCateg.java
  src/main/java/com/gongkademy/infra/s3/service/FileService.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
Labels: ♻️Refactor

#308 Refactor: S3 controller 수정 및 enum 정적 import
  src/main/java/com/gongkademy/infra/s3/S3Controller.java
  src/main/java/com/gongkademy/infra/s3/service/S3FileService.java
Labels: ♻️Refactor

#310 Refactor : s3 controller 어노테이션 및 예외 처리
  src/main/java/com/gongkademy/global/exception/ErrorCode.java
  src/main/java/com/gongkademy/infra/s3/S3Controller.java
Labels: ♻️Refactor
